package no.javabook.dijoe.exceptions;

public abstract class DIException extends RuntimeException {

	/**
	 * autogenerated
	 */
	private static final long serialVersionUID = -9142168086959751771L;
	
	private final Class<?> requestedClass;
	
	public DIException(Class<?> requestedClass, String message) {
		super(message);
		this.requestedClass = requestedClass;
	}

	public DIException(Class<?> requestedClass, Throwable cause) {
		super(cause);
		this.requestedClass = requestedClass;
	}

	public DIException(Class<?> requestedClass, String message, Throwable cause) {
		super(message, cause);
		this.requestedClass = requestedClass;
	}
	
	public Class<?> getRequestedClass() {
		return requestedClass;
	}


}
