package no.javabook.dijoe.exceptions;

public class NoBoundSingletonException extends DIException {

	/**
	 * autogenerated
	 */
	private static final long serialVersionUID = -3747072097296759917L;

	public NoBoundSingletonException(Class<?> requestedClass, String message) {
		super(requestedClass, message);
	}

	public NoBoundSingletonException(Class<?> requestedClass, Throwable cause) {
		super(requestedClass, cause);
	}

	public NoBoundSingletonException(Class<?> requestedClass, String message, Throwable cause) {
		super(requestedClass, message, cause);
	}

}
