package no.haakon.wsdif;

public class ConstructorWontBuildException extends RuntimeException {

	/**
	 * autogenerated
	 */
	private static final long serialVersionUID = 8401440440049733973L;

	public ConstructorWontBuildException(String message) {
		super(message);
	}

	public ConstructorWontBuildException(Throwable cause) {
		super(cause);
	}

	public ConstructorWontBuildException(String message, Throwable cause) {
		super(message, cause);
	}
}
