package no.haakon.wsdif;

public class NoSuchClassBoundException extends RuntimeException {

	/**
	 * autogenerated svUID
	 */
	private static final long serialVersionUID = 747849806018646806L;

	public NoSuchClassBoundException(String message) {
		super(message);
	}

	public NoSuchClassBoundException(Throwable reason) {
		super(reason);
	}

	public NoSuchClassBoundException(String message, Throwable reason) {
		super(message, reason);
	}

}
